name: Create GitHub Release

on:
  push:
    branches:
      - main

jobs:
  create_release:
    if: startsWith(github.head_ref, 'release-')
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Extract release branch name
      - name: Set release branch name
        run: echo "RELEASE_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      # Create GitHub release
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_BRANCH }}
          release_name: ${{ env.RELEASE_BRANCH }}
          body: |
            Release based on merging branch ${{ env.RELEASE_BRANCH }} into main.
          draft: false
          prerelease: false

